<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{08a3c80a-9d54-4bd3-a860-80de0df9675b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Control_LD();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>